name: abs_customer_sites
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_snake_navigationbar: ^0.5.0
  cupertino_icons: ^1.0.2
  get_it: ^6.0.0
  get: ^4.1.3
  file_picker: ^3.0.1
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.0
  flutter_swiper: ^1.1.6
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  sliding_card: ^0.1.2
  camera: ^0.8.1
  motion_sensors: ^0.1.0
  kt_dart: ^0.9.0
  better_player: ^0.0.65
  video_player: ^2.1.1
  flutter_zoom_drawer: ^2.0.1
  shared_preferences: ^2.0.5
  aeyrium_sensor: ^1.0.7
  hydrated_bloc: ^7.0.0
  path_provider: ^2.0.1
  flutter_native_image: ^0.0.6
  video_thumbnail: ^0.3.3
  dio: ^4.0.0
  advance_pdf_viewer: 
    git:
      url: https://github.com/real-john-doe/pdf_viewer.git
  adaptive_dialog: ^0.10.0+5
  extended_image: ^4.0.1
  flutter_secure_storage: ^4.1.0
  local_auth: ^1.1.4
  loading_overlay: ^0.3.0
  image_picker: ^0.7.4
  top_snackbar_flutter: ^1.0.0
  uni_links: ^0.5.1
  checkbox_grouped: ^1.4.0
  flutter_svg: ^0.22.0
  dio_cookie_manager: ^2.0.0

 
  
  




dev_dependencies:
  flutter_test:
    sdk: flutter
  faker: ^2.0.0-rc.2
  pretty_dio_logger: ^1.2.0-beta-1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

    # to add svg files check the svg configuration : set "styling" to "Presentation Attributes" , 
    # set "images" to "Embded" . To check it you can open svg file in adobe illustrator and follow steps:
    # File > Export > save for screen > Format (Gear icon) > SVG and then change the configuration

  assets:
    - assets/car-preview.png
    - assets/verified.png
    - assets/logo.png
    - assets/images/seen.svg
    - assets/images/not-seen.svg
    - assets/images/book-appointment.svg
    - assets/images/car-finder.svg
    - assets/images/contact-us.svg
    - assets/images/order-part.svg
    - assets/images/service-appointment.svg
    - assets/images/value-trade.svg
    


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
